version: '3.8'
services:
  gateway:
    build:
      context: gateway
    container_name: shareit-gateway
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    container_name: shareit-server
    build:
      context: server
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SERVER_PORT=9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/test
      - SPRING_DATASOURCE_USERNAME=test
      - SPRING_DATASOURCE_PASSWORD=test
      - TZ=Europe/Moscow

  db:
    image: postgres:13.7-alpine
    container_name: database
    volumes:
      - ./server/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/create_db.sql
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test